### ISSUE TITLE
"EFF now controls the Electronicfrontierfoundation.org"

### ISSUE THREAD

**Issue by hook54321a** [CHEF-KOCH/NSABlocklist#10]
https://www.eff.org/deeplinks/2015/08/new-spear-phishing-campaign-pretends-be-eff
Although I'm not sure if there is a benefit in unblocking it or not.

**Comment by hook54321a** [comment]
How is this invalid?

**Comment by CHEF-KOCH** [comment]
It's not related to my project and not covered here. Pishing is another own topic, which I'll cover in my other project.

**Comment by hook54321a** [comment]
Why is "0.0.0.0 electronicfrontierfoundation.org" in the hosts file in the first place if it's not related to this project?

**Comment by CHEF-KOCH** [comment]
Because it's a mistake, you simply had mentioned this and I corrected it.

Thanks I'll fix that asap.
