### ISSUE TITLE
Cloudflare ends CAPTCHA challenges for Tor users

### ISSUE THREAD

**Issue by CHEF-KOCH** [CHEF-KOCH/NSABlocklist#18]
> Cloudflare launched today a new service named the "Cloudflare Onion Service" that can distinguish between bots and legitimate Tor traffic. The main advantage of this new service is that Tor users will see far less, or even no CAPTCHAs when accessing a Cloudflare-protected website via the Tor Browser.
> 
> The new Cloudflare Onion Service needed the Tor team to make "a small tweak in the Tor binary," hence it will only work with recent versions of the Tro Browser --the Tor Browser 8.0 and the new Tor Browser for Android, both launched earlier this month.
> 
> Tor users who are dead tired of seeing an endless stream of Google reCAPTCHAs when accessing a Cloudflare-protected site are advised to update to one of these two versions.
> 
> 
> The new Cloudflare Onion Service is also free for all Cloudflare customers and can be enabled by switching on the "Opportunistic Encryption" option under the Crypto tab of the Cloudflare dashboard.
> 
> Tor users have been complaining about seeing too many CAPTCHAs when accessing a Cloudflare-protect site for years now. In February 2016, Tor Project administrators went as far as to accuse Cloudflare of "sabotaging Tor traffic" by forcing Tor users to solve CAPTCHA fields ten times or more, in some cases.
> 
> Cloudflare responded to accusations a month later, claiming the company was only showing CAPTCHAs because 94 percent of all Tor traffic was either automated bots or originating from malicious actors.

Source:
* https://www.zdnet.com/article/cloudflare-ends-captcha-challenges-for-tor-users/#ftag=RSSbaffb68
* https://blog.cloudflare.com/cloudflare-onion-service/

### My finding(s)
* Tor browser Bundle 8.0.1 was removed from download dir ([released 19.09.2018](https://dist.torproject.org/torbrowser/8.0.1/))  `torbrowser-install-win64-8.0.1_en-US.exe` SHA3-256: `FFE3B6598226E1F84D5C1EAF5EC6B4A42FFDA83B88209D9CB8F232C38F76E51E` - sadly I didn't made mirrors for all binaries -> _dayum!_ ([Mirror](https://mega.nz/#!YQ0wBCqC!6nsxxQPgpccXWhwmtXy_jcqfNWCPTUdMND9xl_8jFF4)) - [Re-Release 24. Sept. 2018](https://gitweb.torproject.org/builders/tor-browser-build.git/plain/projects/tor-browser/Bundle-Data/Docs/ChangeLog.txt?h=maint-8.0) Edit: Official download back again (new checksums!) - and it's now on {Tor Blog](https://blog.torproject.org/new-release-tor-browser-801).
* No source code provided, does this means cloudflare spies now within the Browser in order to identify you ?!
* The "rendezvous point" is another word for man-in-the-middle (see also Cloudflare Blog picture)
* Problem isn't solved (also mentioned in the Blog post)
* The Wrong configuration leads into privacy risks
* Yet again [all stands and falls with certificates](https://cabforum.org/pipermail/public/2017-November/012451.html)
* People are forced to use Tor browser 8.x otherwise they still get reCAPTCHA spam
* The [promised add-on](https://github.com/cloudflare/challenge-bypass-specification) would be better since everyone can decide/uninstall/use it or not. It's a bad idea to implement something (which needs optional enabled on every cloudflare provided website) when not everyone needs it, from my experience, not every page needs 'special' protection starts with forums - it makes more sense to harden them against DDOS without any reCaptchas because legitimate users get pissed off.

## Some stupid arguments coming from CloudFlare 

> Therefore it is important to use HTTPS Everywhere to secure the first request.

An add-on is a risk since it can be manipulated, just because the website uses a server to client encryption doesn't mean the website is 'safe'. Certificate/DNS queries are fakable + the data within the website might not be encrypted at all. HTTPS Everywhere collects additional info from it's user aka Browser History (later they obfuscated this after I asked them why they 'spy' - see [here](https://github.com/EFForg/https-everywhere/issues/2428) -> now you see 127.0.0.1 queries in the developer console which obfuscates the url's to an 'optional' domain [even after you opt-out of all things). @EFF why is your spying better than googles or cloudflares?! **The Browser itself** should try to use HTTPS in the first place, not an addon. Seems in 2018 still a mission impossible. _What a shame_!

> Once the browser receives this header, it attempts to make a new Tor circuit to the onion service advertised in the alt-svc header and confirm that the server listening on virtual port 443 can present a valid certificate for “cloudflare.com” — that is, the original hostname, not the .onion address.

Header manipulation is still possible, DNS is only _secure_ if e.g. DNSSEC is involved, lots of websites still don't use/enabled it for several reasons which mean specific queries can be manipulated. This is not only a theory and proven, as (yet again) shown [here](https://www.heise.de/security/meldung/Zertifikate-fuer-beliebige-Domain-Forscher-demonstrieren-kritisches-DNS-Problem-4156868.html). This might allow the attacker to fake certificate requests, the info which is shown in the Browser is then 'incorrect', which means user which are depending on this might get fooled. 

> Onion Routing is now available to all Cloudflare customers, enabled by default for Free and Pro plans. The option is available in the Crypto tab of the Cloudflare dashboard.

Nice, push your own stuff, but how it helps other services if it's not implemented directly into as a common standard?! Right, in other words, you advertise (yet again) your own created stuff as 'secure'. So how you're better than Google & Amazon which also pushing their own technologies into the web.

> You can check whether your connection is routed through an onion service or not in the Developer Tools window under the Network tab.

A normal user never opens the developer console and not even reporter (there often a huge target), because no one like to waste time with this. It's not a reliable option anyway because even if you monitor it a normal user simply doesn't understand it. This must be implemented within e.g. the security slider as 'noob proof' visible indicator or something which is understandable via [pictograms](https://en.wikipedia.org/wiki/Pictogram). 

> As we maintain and improve this service we will share what we learn. In the meanwhile, feel free to try out this idea on Caddy and reach out to us with any comments or suggestions that you might have.

Then please mark it as 'beta' or indicate that this is more or less a test until all 'problems' are fixed. 

>Tor users who are dead tired of seeing an endless stream of Google reCAPTCHAs ... 

As [Atavic mentioned](https://github.com/CHEF-KOCH/NSABlocklist/issues/18#issuecomment-423271835) it's a bad advice because reCaptcha itself stands and falls with JS. However, rather than saying '_Google sucks_' how about working with them together to improve the reCaptcha problem in order to fix it for everyone?!  

Ref:
* https://news.softpedia.com/news/cloudflare-looking-into-new-system-that-removes-captchas-for-tor-users-508898.shtml (2016)
* https://cryptome.org/2016/07/cloudflare-de-anons-tor.htm (2016)
* https://tw.saowen.com/a/f2d78cca479e7a4bd02df2a4c6aed43c3d4b041b88e8724bc14f0c91ad01147a
* https://yro.slashdot.org/story/16/02/26/1816211/tor-project-accuses-cloudflare-of-mass-surveillance-sabotaging-traffic  (2016)
* https://support.cloudflare.com/hc/en-us/articles/203306930-Does-Cloudflare-block-Tor-
* http://www.delaat.net/rp/2016-2017/p55/report.pdf  (2016)
* https://tor.stackexchange.com/questions/4441/does-cloudflare-identify-tor-users-actual-ip-address-and-other-identifying-info
* https://blog.cloudflare.com/privacy-pass-the-math/
* https://www.cypherpunks.ca/~iang/pubs/privacypass-popets18.pdf
* https://blog.cloudflare.com/esni/

**Comment by Atavic** [comment]
reCAPTCHA needs JS to be enabled, so this "Cloudflare Onion Service" needs to lower the Security Slide Setting, so lowering the deanonymization efforts available in the Tor Browser.

> Tor users who are dead tired of seeing an endless stream of Google reCAPTCHAs when accessing a Cloudflare-protected site are advised to update to one of these two versions.

Bad advice. Tor users should not browse any Cloudflare-protected site.

Another project that's collapsing in a controlled demolition.

**Comment by Atavic** [comment]
[Here](https://github.com/privacypass/challenge-bypass-extension) I see they implement the  P256 curve.

The SafeCurves web site reports security assessments of various specific curves: https://safecurves.cr.yp.to/

According to these criteria, designed to ensure ECC security, NIST P-256 is not safe to use.

> what about working with them together to improve the reCaptcha problem?

Cloudflare created the problem by using it.

**Comment by CHEF-KOCH** [comment]
The PrivacyPass extension is not official from Cloudflare, [none of them are directly involved](https://privacypass.github.io/team/) into the current cloudflare <-> tor development. The cloudflare team (from what I know) never hold it promises to release a add-on. I'm also unsure about how effective the mention addon is it's still on version 1.0 (Nov 2, 2017) and never got any updates or serious reviews.

According to Daniel J. Bernstein's Safe Curves page [NIST P-256 is not safe](https://safecurves.cr.yp.to/index.html). Tor itself provides Curve25519 which is safe (but _optional_). This is also correct if you check the leaks from [2017](https://cr.yp.to/talks/2013.05.31/slides-dan+tanja-20130531-4x3.pdf) others should be used. 

> Cloudflare created the problem by using it.

I'm not sure, because there is no (real?) alternative.

**Comment by Atavic** [comment]
Yes, that project I linked seems unrelated.

> Addresses used by the Cloudflare Onion Service:

cflare*.onion

They all begin with that string.

**Comment by CHEF-KOCH** [comment]
> They all begin with that string.

There will be only the 10 addresses since the entire traffic goes through all of them (that's by their design check the second picture). Fun thing is that this doesn't secure anything at the end and makes it for the FBI and CIA even harder to catch people (if Cloudflare doesn't decide or forced to give away the possible analyzed traffic which went through their servers). 

I just tested the [re-release of Tor Browser 8.0.1](https://dist.torproject.org/torbrowser/new/8.0.1/) and still get almost the same amount of captchas.

 ![untitled](https://user-images.githubusercontent.com/727123/45901259-9b444000-bde2-11e8-9a13-fe038d2d19c5.png)

Again, I see this as beta and nothing but it + that doesn't solve the issue that some providers forcing you to solve the captcha (if you check Cloudflares blog they added several years back an option to force user to solve captcha before you access their site).

**Comment by CHEF-KOCH** [comment]
I close this ticket since there is nothing to add, whatever this experiment is, it's not going to work and never will be because CloudFlare itself provides an option to protect domains against DOS via reCaptcha. This option is for no reason often activated even for forums (which doesn't make any sense because if that forum has something to hide simply remove it from the Search engine index and that's it [most elite warez board doing this]).

I tested it via:
* Tor 7.x (20 versions)
* Tor 8.x (2 version)
* Tor server running/disabled
* Linux/Windows with Google, CloudFlare & OpenDNS 
* Cookies and cookies enabled/disabled
* JS script enabled disabled (after solving the "initial captcha") 
* Blocked 1/2/3/4/5/6/7/8/9 servers (the Cloudflare ones to see if it changes/breaks something)

None of this changed something any I highly doubt that something can be changed here because of the mentioned argument. It's simply a 'lie' that Cloudflare ends the reCaptcha story here, even if that is bypassed somehow you can bet Google & partners will change this again in order to 'fix' it, the interest for security stands on both side a) user does not like captchas (understandable) but on the other side b) the domain owner wants to protect his domain(s) - and tracking users is (since there is no other solution) the best way to keep 'the bad guys' out.
