### ISSUE TITLE
3 lines at top of host file incomplete?

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [CHEF-KOCH/NSABlocklist#2]
is there a reason these lines at the top arent prefixed by 0.0.0.0 ?
```
adm.kemoge.net
ads.kemoge.net
taosha.cc
```

im trying to use a hosts file merger like you suggested but its complaining about those lines

**Comment by CHEF-KOCH** [comment]
Okay, feel free to edit/pull I gave you access so feel free. No, seems it was my fault.

**Comment by berrythesoftwarecodeprogrammar** [comment]
sorry have been busy recently
