### ISSUE TITLE
ReactOS

### ISSUE THREAD

**Issue by blackcrack** [CHEF-KOCH/NSABlocklist#53]
Hi Peoples,
sorry if i am be wrong (or off-topic) here and to call the Peoples to help for Building Reactos.org fully up to have a WinNT under GPL.
Reactos.org as WinNt under GPL2, could be a possible to hold the Peoples save.
you should looking on Reactos.org again now, have done many.. i have 
monitore in the last Years Reactos.org it grow up slowly but it grow up..
And if you not looking on or doing something to help for faster grow up, with you're knoff hoff,
who else does it .. ?
You are should help to programming it for a faster grow up and finishing
in save form.
Maybe is Reactos in the first way a WinXP conform WinNT, but the 2nd way, 
if have reach version 1.0 is imho open.. and can be better as them of MS WinNT.

you could build in a shielding from NSA Servers and others 
and a anti-Malware to defence facilities/Shild against various states where whont spy a WinNT ordering system.
Directly build in in Reactos and enable with a registry switch/key.

The other thing.. => Hidden Printer dots, direktly build in the Reactos.
also enabling with a registry Key, so why not..
any can make with programming and bring in Patches at reactos here in Github ;)
Reactos computer as Router.. like in WinNT from M$WinNT, but more save..
if you are Programming with...

This could be a possible to have a really good WinNt
in form of Reactos.org 
(Reaction to the MS Ordering System 
{for a more save, more independent system and a real open WinNT Kernel}) .

best Regards
Blacky

----------------------------
Hi Chefkoch,

https://github.com/CHEF-KOCH/NSABlocklist/issues/53

if there exist a WinNT Group, why not support a build up of WinNT out of the Internetcommunity to take that Toy and Moneymaker out of the Hand from Microsoft.

The always build up a new Windows,  pushing support for the current version and stopping that WinNT version.. and stop a support for this "Windowsversion" because to sell Support to the factory's and let open the backdoors or possibility's for US facilities what it is wrote in the US law's..
the whole things behind that make the MS-WinNT not more really secure ..

The Reactos.org community will stay.. and stay behind the whole update like the way want go..
and dropping support, why.. it is only a making money thing and politic of it.. or behind of it..

that's not only why..  build up Reactos.. and not only because the dropping of Support like now and in the past XP, it's much more  .. ask friends to help with, then can you say.. "not with me"
because we have Reactos .. out of the Internet community .. under GPL2 for free and as free/open source software up to the NT-Kernel in any corner ..

best regards
Blacky

**Comment by CHEF-KOCH** [comment]
Sorry, I don't understand what your point is.

**Comment by blackcrack** [comment]
Hi Chefkoch

merging :+1:  .. and the backdoors okey.. you be more known about programming and so on like i guess ..

"... a ripoff of the Windows Research Kernel', claims Microsoft kernel engineer"
and you just believe it easy.. did you researched and looked at yourself ?
I can also many claim, if the day long..
You food easy all what someone put before you  ?
Did you go into the IRC and have speak about with the Reactos Programmers and have investigate by self ?
Reactos hast started with Freewin, Win95 blending as Live"system" on disk or something..

And i say you, Microsoft Windows is coming from the outer Space and is build up by Aliens !
The Microsoft Windows Source code is stolen from a Space Ship ! 
And Axel Rietschin is a Alien .. and suck his food out of the fingers \*giggle

But that's true: And the Dos-Programmer have never get director's fee (and Bill makes  Millions of dollars therewith) ...

the point is, help Reactos/Help to build up Reactos if you can programming,
and you help yourself and many others to have later a independent
WinNT Orderingsystem out of the (internet)Community from they are 
where be in able to programming. 
My crux is, i have never learning in the last 20 Years to programming 
(and this a bit sh/bash, dos/Win/batch and php can not name programming in c,c++,pascal and other way), 
i was ever the part who have it used/applied and distributed (1:2 or so on) in private way, but i have see many therewith.. i have watch the way of Reactos WinNT (out of the Internet community) since ~ 2000 (before freewin) and must say, if we not put us own ass out of the  "new version of Windows and Support end" -Gameplay/Sauce, does ever goes on the MS-Game to make money and give the Microsoft in the States (and the whole world) different possibility's to make a bad Politic for Peoples who want independence and want have safety and security at home, in the computers and software
and a fast as possibility update and security patches we are all who work with WinNT be are depended at moment to the WinNt from Microsoft and this can change . 

You are angry (and puke around) over a support end of WinXP and Windows 7
i guess, we are not alone .. 
you must only support Reactos to have a really free and open source WinNt.
And it is open source can many see the source code and can have trust in plainness of open source.
It doesn't mean it can be changed by anyone, it just says that everyone can see it
and have the possibility to fix it and bring fixes in .. 

this is the point, like i guess ..

best regards
Blacky :)

**Comment by CHEF-KOCH** [comment]
The discussion is pointless, I do not support ReactOS not do I consider it as a replacement for Microsoft's Windows. I'm not against the "open source" Windows idea however, I seriously doubt that [releasing the code makes something more trustworthy](https://www.theinquirer.net/inquirer/news/3073749/backdoor-in-popular-open-source-tool-put-28-million-users-at-risk). 

Just because there is the source doesn't mean it gets audited and just because you are capable of compiling it doesn't mean you understand how secure or insecure the code is. Coding and auditing software are two seperate things and there are many examples when open source "failed" e.g. [OpenSSL](https://en.wikipedia.org/wiki/Heartbleed).

If there are security or privacy concerns then use one of the mentioned OS alternatives like [Quobes OS](https://www.qubes-os.org/). If you goal is that I list ReactOS as replacement for Windows then I have to dissapoint you, it will never happen simply due to the fact that the React Core is years behind the current MS Windows kernel.

**Comment by blackcrack** [comment]
Hi Chefkoch :smiley: 
well, the fully open source the code, deep in WinNt kernel, make it more trustable imho, therewith it's known what's inside .... the MS-Kernel is it not.. and parts be never open for the public..

but on openssl it's now known.. and libressl exist ..

but could be a alternate for XP, i know, outdated, but at least :)

oky :) thank you for your nice conversation 
therewith close i am the "issue" if it's okey :)

best regards
Blacky

**Comment by CHEF-KOCH** [comment]
I doubt anyone really compiles the Windows kernel even if it would be open source. Compiling my Kernel for my Android phone alone takes 45 minutes, I only can imagine how long it would take to compile the Windows Kernel.

> ...."parts be never open for the public"

Microsoft already [open sourced a lot programs](https://github.com/microsoft) and [took over GitHub](https://news.microsoft.com/2018/06/04/microsoft-to-acquire-github-for-7-5-billion/) which basically gives them unlimited access to all repos. I think soon or later Windows itself will be open source, .NET framework is already open source, the "bash" clone for Ubuntu (Linux) is open, Powershell, and many other programs. The thing is that once [MS opens the code](https://www.techradar.com/news/windows-core-os-could-be-partially-open-source), people would steal it and re-pack, re-name and distrurb their "improved" Windows versions over the Internet. uBlock is an good example, it's FOSS and [people faking it to introduce it under differnt names across the stores to e.g. steal or crypto-mine user data](https://www.tomshardware.com/news/adblock-ublock-fake-google-chrome-browser-extensions,40422.html),** this is a huge problem. 

Another problem is that no one really makes money with open source while the people at MS wants to get paid for their hard work. I see this critical when it comes to "money". In my opinion everyone deserves to get paid for their work.

**Comment by blackcrack** [comment]
well,

a Linuxkernel have many drivers into and a WinNtKernel have the most drivers out of the kernels and is ... ?monologic ? and it is also a diffrent between microkernel and an linuxkernel.. on Mandrake Times have i am build my kernel byself (~1999/2000) .. but with the whole coming extra patches by Mandriva and now at openmandriva, I thankfully renounce it .. a kernel is at WinNt compiled once per version and the other things makes the Hardwaredrivers of the manufacturers, therefor it's a computer in the corner as kernelbuilder enough.. and if you push die computing power with a nvidia-Grafik's card or so, i think on a 1075 titan or so, it's really easy to have a kernel by day.. i guess ..
well, what should i say ;) 

yes, today.. because they have see to be Open source also a moneymaker, if it is make right ..
and clear, think you i be blind.. this with the Github.. many have protests against it..
and it is opened the Dos.. have becomes all with, i hear the sough.. behind the 20 jears have i learned also like you.. but i was never in the "konsum & Money makeing world" and have let me not blend.. because i had ever hold my computer as hobby.. okey, i lay .. i was a half/one year in a Computer Shop as systems consultant and Shop Manager a couples times, on this times was i am also in the high times of lan area networks over a fritz-card on different big "Mailboxes/BBS's", you can trust me, i have become with, what's all goes on..
This is also the reason why i am not in Facebook, don't cryptomine and other things, because i want me stay true to myself and be in pure with me .. and not ending as a hunted death meat ..

and you see it a bit wrong, you be in able to make money with Open Source, but not really with the software by self, more with the work what you really makes.. the software as own is it doesn't really matter, because it is sell the Work, so the Time of you work sell it and not 1000th of 1000th copy's and so on.. with inflated/excessive prices for one f... Software copy , clear, the whole peoples must be pay and they kid's must be supported and the Wives must pay the Shoes \*giggle ..
but it can not goes on to take 100 Euros or maybe 120 Dollars for one f.. Softwarecopy at more as 1Million Softwarecopy's .. sorry Dude .. imho .... this can not be... .. okey, i see the Homepage of Pixels.. and the Peoples make with.. any pixel a Dollar or so.. and it has work, this Dude is now a Millionaire..
It was a cool idea, I do not begrudge it !  But stealing software and change it and do not a correckt work, it's really not okey, yes, this is bad imho, because there put work into and an other mean he must easy come on, take them works and make it for it self easy and sell it again, that's bad because he self have don't bring work into it and make cash again without bring work into in.. and with a foreign work, this name i am also steal .. some peoples say maybe .. why i compilation.. bunkum, the computer does it and he bring nothing intelligent into code because he have no idea's and bring not in fresh informations by independent consideration,reflection and assembly.. and takes from an other.. 
and say it's them self works.. yes, this is a asshole .. and steal code .. right..

But, like i told, i have watch in the last years Reactos and believe me, i have become from the most changes mails and see what's changed and be most small codepard's, they are really programming reactos and do not steal the code.. if you really know it by self, do investigate, and programming with, make friends in Reactos and overwatch it by self and don't take easy opinions from peoples who cry around in a "Newsletter"  and in the internet, "These Reactos is stole and it is bad" they can not do that.. building up a WinNt it is simply impossible tp programming self a kernel and a WinNt.. i say simply.. : Blubb !! it's simply mud what's comes out of the neck opening .. and the "want" behind.. "don't use and trust reactos and don't help to build up reactos" .. is the want behind it..

Make your own Opinion and investigate by self and take not easy a opinion from anyone Foreign Person .

MS WinNt want may someday Open Source, but this is a Version where can anyone see what's in it and WinXP, Win7 and 8.1 it then gone ! and the sources moldy somewhere in a Tresor of MS deep in the basement, because it is not allowed to get out of it all what's was happens ! In the past ..

sorry for my bad english \*grin* but i hope you see what i meant ..

but 2nd, pay for his work, see i the same and stand fully behind...
And pay work out of support it's also possible, like .. we have a Ordering System (no matter what for a system) in a Factory and there is a need for support and further developing.. and patching and so on.. therewith can you make money.. in the backstage .. for supporting a Factory and pay the time ..
with something it's also possible to make money.. and this is "real" work and therewith also fair making money..  this software can be open source for the community and a faster developing..
A faster developing as could it be in copyrighted "softwarecopys" and Patents and where are have to pay the patens and the single patent can only used because it is not CC/GPL'ed and the front of peoples can not developing with it, because it is "copyrighted" and owned by a "single Person"(can also be a Factory) and this is the "Problem/Task" behind it.. if you want see the whole thing..

and from there comes also the whole thing.. Buy a software-copy... because you become the rights to use for it.. and it is not open sources.. because is commercial used software in more as one way..

and keeps/stops many developments ... the whole commercial thing in it .. in Software and wissen..
the knowing should be free but not stole ...
The own/actual developer should profit from it !  Think on The Dos-Guy .. Bill has stolen imho, maybe has he give a bit money, but the Head-Developer did not get any Developer Fee (Tantiemes or so) ! (like i have become with.. can also be a wrong Information..)

So, investigate by self on Reactos and looking on the work.. maybe could you support your self if you a bit programming with..

best regards
Blacky
