### ISSUE TITLE
mobilesyrup.com

### ISSUE THREAD

**Issue by p1r473** [CHEF-KOCH/NSABlocklist#69]
This is a news site and not owned by the NSA ;)

**Comment by CHEF-KOCH** [comment]
Even "news site" can be faked, compromised or secretly infiltrated. 

Claiming "not owned by NSA" (no one actually said anything that the listed pages are "owned" by NSA btw) is a bit thin.

I have to investigate into this, since you provide no actual proof.

**Comment by edinjapan** [comment]
@CHEF-KOCH what makes you think this website is related to NSA?
This is a popular Canadian news site that covers tech topics and review of new phones, laptops, etc.
