### ISSUE TITLE
Bahnhof?

### ISSUE THREAD

**Issue by k3anton** [CHEF-KOCH/NSABlocklist#7]
Hi,

I'd like to question why Bahnhof.se is added, more specifically:

> 0.0.0.0 auto-ns.bahnhof.net
0.0.0.0 ns2.bahnhof.net
0.0.0.0 ns.bahnhof.se

I urge you to read up on Bahnhof as a company here: https://en.wikipedia.org/wiki/Bahnhof

Some citations include but not limited to: 

> In 2009, Bahnhof generated controversy by failing to store the IP addresses of customers, in order to defeat the Swedish government's new laws on illegal file-sharing, transposing the EU IPRED regulations, which enabled ISPs to retain data longer than the data protection regulations would allow, in order for them to be available on police request.[12] Source: [Wikipedia](https://en.wikipedia.org/wiki/Bahnhof)

> In April 2014, however, the CJEU struck down the Data Retention Directive. PTS, Sweden's telecommunications regulator, told Swedish ISPs and telcos that they would no longer have to retain call records and internet metadata.[13] But after two government investigations found that Sweden's data retention law did not break its obligations to the European Convention on Human Rights, the PTS reversed course.[14] Most of Sweden's major telecommunications companies complied immediately, though Tele2 lodged an unsuccessful appeal. Bahnhof was the one holdout and it was given an order to comply by November 24 deadline or face a five million kronor ($680,000) fine.[15] **In response Bahnhof offered all their customers a free VPN-service, thus making it impossible for Bahnhof to hand over customer data to law enforcement.**[16] Source: [Wikipedia](https://en.wikipedia.org/wiki/Bahnhof)

Since I lack knowledge of why it was put on the NSABlocklist, I can't really argue why it shouldn't be there but I feel that I can contribute information on the company behind those addresses. Bahnhof has always been recognized as a company that fight privacy intrusive operations by the EU or by the Swedish government. It tries to protect its customers by offering VPN services and limit the amount of data being stored ([by law](https://en.wikipedia.org/wiki/Data_Retention_Directive)) about their customers. 

Best regards,

**Comment by Atavic** [comment]
Sweden is part of The Fourteen Eyes with Germany, Belgium, Italy and Spain.
Bahnhof swedish ISP has been listed as _NSA Friendly_ in 2007.
