### ISSUE TITLE
bethesda.net

### ISSUE THREAD

**Issue by p1r473** [CHEF-KOCH/NSABlocklist#70]
This is a gaming company :)
I do not think they are a part of the NSA.

**Comment by CHEF-KOCH** [comment]
Bethesda.net is not even on the list, you get banned now for wasting my time and the troll effort.

**Comment by edinjapan** [comment]
https://github.com/CHEF-KOCH/NSABlocklist/blob/master/HOSTS/Trackers/canvas%20fingerprinting%20pages.txt#L1442

Are you serious? You ban the last guy for reporting false positive, and you did not even search your repository before BANNING him????? Then you accuse him of trolling???? 
You should not ban people for this. You know ban is permanent. And that guy has provided very many good false positive report to you so far.... Seriously, unban him, he is helping our community fix blacklists that have false positives.

![image](https://user-images.githubusercontent.com/59746332/77828675-3cf0cf80-70f3-11ea-8adf-8208c5089c5c.png)


This is a videogame company. Should not be blocked.
