### ISSUE TITLE
List based on questionable source

### ISSUE THREAD

**Issue by eleius** [CHEF-KOCH/NSABlocklist#82]
Your main source, which in https://github.com/CHEF-KOCH/NSABlocklist/issues/81 you claimed to be completely trustworthy, "reviewed and checked", appears to be http://cryptome.info/nsa-ip-update10.htm

From the same page:

> "**A, like others, questions the validity of these NSA-Affiliated IP lists** . . . My view: The Internet continues to be a minefield of disinfo and deception, completely untrustworthy"

**Comment by CHEF-KOCH** [comment]
You quote something out of context, nor is a private conversation a basis for a discussion. We all know that internet spreads misinformation, what is the news?

The list was before and afterwards checked based on all leaks from back then + the new findings back from the known NSA leaks. 

Can YOU prove that this is fake? Did you contact cryptome? And why would someone go trough all instances and waste his own lifetime posting super-ranges which are simply checkable via whois + owner Info + Domain check (which I did back then).

**Comment by eleius** [comment]
Again, concerns have been raised several times, for example http://cryptome.info/nsa-ip-update3.htm and elsewhere in those lists. And here we go again with the invalid flag. Bye.

**Comment by CHEF-KOCH** [comment]
Because as said, this is not the full conversation and in [other documents](https://cryptome.org/ip-tla.htm) it clearly states that the ip's and domains are connected to the "Terrorist Surveillance Program".

Bring here real evidence and not private doubt, then I unlock the conversation.
